"""Refuse a PR whose description says nothing and names no issue.

Extracted from `.github/workflows/pr-lint.yml` (#963), where it was 65 lines of
untested logic in a heredoc — the one shape keel's pure-core/thin-I/O rule in
`AGENTS.md` exists to prevent. `description_errors` is pure and takes everything
it needs as arguments; `main` is the only part that touches the environment.

The bot exemption is the reason for the extraction. Asserting it from the
workflow's *text* would prove the string is present, not that the rule holds in
either direction — and an exemption that swallows every PR is worse than the
block it replaces.
"""

from __future__ import annotations

import os
import pathlib
import re
import sys

#: Minimum characters of the author's own prose. Short enough that a one-line
#: summary passes, long enough that "fix" does not.
MIN_PROSE = 20


def strip_comments(text: str) -> str:
    return re.sub(r"<!--.*?-->", "", text, flags=re.S)


def is_bot(author_type: str) -> bool:
    """True for a GitHub App account, whose PR body it does not author.

    dependabot's body is a changelog excerpt generated by GitHub; it carries no
    issue reference and cannot be taught to. Before this exemption every
    dependabot PR was permanently unmergeable, which turned ``idna`` and
    ``lxml`` security bumps into a backlog nobody worked through (#963).

    Keyed on ``user.type``, GitHub's own classification, rather than on the
    login. A list of known bot names goes stale on the second bot, and matching
    the reserved ``[bot]`` suffix is a naming convention standing in for the
    fact it encodes. Confirmed against the API for a real dependabot PR:

        user.login = dependabot[bot]   type = Bot

    Note that ``gh pr view --json author`` renders the same account as
    ``app/dependabot``; the event payload this reads carries the API's value,
    not the CLI's. Anything keyed on the login has to know that, and this does
    not have to.
    """
    return author_type == "Bot"


def description_errors(body: str, template: str = "") -> list[str]:
    """Every reason to refuse this description; empty means it passes."""
    # Strip the template's HTML guidance FIRST: the issue-reference and opt-out
    # checks must look at AUTHORED text only, otherwise the comment's own
    # "#N"/"no issue" guidance would satisfy them for every default PR.
    authored = strip_comments(body)

    # Lines the author left exactly as the template shipped them (the prose
    # placeholder, checklist rows, headings) don't count as a real summary.
    boilerplate = {
        line.strip()
        for line in strip_comments(template).splitlines()
        if line.strip()
    }

    prose = []
    for line in authored.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if re.match(r"#{1,6}\s", stripped):            # markdown heading (not "#123")
            continue
        if re.match(r"^[-*]\s*\[[ xX]\]", stripped):   # "- [ ] ..." checklist row
            continue
        if stripped in boilerplate:                    # unchanged template line
            continue
        prose.append(stripped)
    summary = " ".join(prose).strip()

    # Issue reference: a real "#<number>", or the explicit "no issue" opt-out —
    # searched in the authored (comment-stripped) text only.
    has_ref = bool(re.search(r"#\d+", authored)) or bool(
        re.search(r"\bno[ -]?issue\b", authored, re.I)
    )

    errors = []
    if len(summary) < MIN_PROSE:
        errors.append(
            "description is empty, unchanged from the template, or too short "
            f"— write a real summary (>= {MIN_PROSE} chars of your own prose)."
        )
    if not has_ref:
        errors.append(
            "no linked issue — add 'Closes #N' (or 'Relates to #N'), "
            "or write 'no issue' if this PR genuinely touches none."
        )
    return errors


def main() -> int:  # pragma: no cover - the I/O shell; the rules above are tested
    author = os.environ.get("PR_AUTHOR", "") or ""
    if is_bot(os.environ.get("PR_AUTHOR_TYPE", "") or ""):
        print(f"PR description OK: {author} is a bot, whose body GitHub generates.")
        return 0

    template = ""
    path = pathlib.Path(".github/pull_request_template.md")
    if path.exists():
        template = path.read_text(encoding="utf-8")

    errors = description_errors(os.environ.get("PR_BODY", "") or "", template)
    if errors:
        print("PR description lint failed:")
        for error in errors:
            print(f"  - {error}")
        print(
            "\nEdit the PR description to fix these. See the PR template's "
            "'Summary' and 'Related issues' sections."
        )
        return 1
    print("PR description OK: has a summary and an issue reference.")
    return 0


if __name__ == "__main__":  # pragma: no cover - entry point
    sys.exit(main())
