"""The PR description lint, including the bot exemption #963 added.

Before it, `PR has a real description + linked issue` refused every dependabot
PR: the check accepts a real `#N` or the explicit `no issue` opt-out, and
dependabot's body — generated by GitHub — carries neither and cannot be taught
to. Three bumps were sitting unmergeable, two of them (`idna`, `lxml`) the kind
of dependency whose releases are often security fixes.

An exemption is only as good as the case it does *not* cover, so both directions
are asserted here. The rules were extracted from a heredoc in the workflow to
make that possible: asserting against the workflow's text would prove the string
is present, not that a human PR with the same empty body is still refused.
"""

from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / ".github" / "scripts" / "pr_description_lint.py"


def _load():
    """Import the script by path — it is not part of the installed package."""
    spec = importlib.util.spec_from_file_location("pr_description_lint", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


lint = _load()

GOOD_BODY = "This rewires the evidence gate so a waiting check blocks. Closes #963."


class TheBotExemption(unittest.TestCase):
    def test_a_bot_account_is_exempt(self):
        """`Bot` is what the API reports for dependabot; verified on PR #918."""
        self.assertTrue(lint.is_bot("Bot"))

    def test_a_human_is_not_exempt(self):
        """The half that matters: an exemption that swallows everything is worse
        than the block it replaces."""
        self.assertFalse(lint.is_bot("User"))
        self.assertFalse(lint.is_bot("Organization"))

    def test_a_missing_type_is_not_exempt(self):
        """Fail closed: an absent `PR_AUTHOR_TYPE` must not exempt everyone."""
        self.assertFalse(lint.is_bot(""))

    def test_the_exemption_does_not_read_the_login(self):
        """Keyed on GitHub's classification, so no username can claim it.

        A login-based rule has to reason about which name shapes are reserved;
        this one cannot be reached by any name at all. Asserted by passing the
        real bot's login as the type and requiring a refusal.
        """
        self.assertFalse(lint.is_bot("dependabot[bot]"))
        self.assertFalse(lint.is_bot("bot"))

    def test_the_exemption_is_not_a_hand_kept_list(self):
        """A list of known bot names goes stale on the second bot.

        Asserted behaviourally: an App nobody has heard of is exempt because of
        what it *is*, not because it was listed.
        """
        self.assertTrue(lint.is_bot("Bot"))
        self.assertNotIn("dependabot", SCRIPT.read_text(encoding="utf-8").split('"""')[0])


class TheDescriptionRules(unittest.TestCase):
    def test_a_real_description_with_an_issue_passes(self):
        self.assertEqual(lint.description_errors(GOOD_BODY), [])

    def test_an_empty_body_is_refused_for_both_reasons(self):
        errors = lint.description_errors("")
        self.assertEqual(len(errors), 2)

    def test_prose_without_an_issue_is_refused(self):
        errors = lint.description_errors("A perfectly reasonable summary of the change.")
        self.assertEqual(len(errors), 1)
        self.assertIn("no linked issue", errors[0])

    def test_an_issue_without_prose_is_refused(self):
        errors = lint.description_errors("Closes #963.")
        self.assertEqual(len(errors), 1)
        self.assertIn("too short", errors[0])

    def test_the_no_issue_opt_out_is_accepted(self):
        for spelling in ("no issue", "No Issue", "no-issue"):
            with self.subTest(spelling=spelling):
                body = f"A genuine summary of a change that touches nothing filed. {spelling}."
                self.assertEqual(lint.description_errors(body), [])

    def test_guidance_inside_an_html_comment_does_not_satisfy_the_check(self):
        """The template's own `#N` hint would otherwise pass every default PR."""
        body = "<!-- Add 'Closes #123' here, or write 'no issue'. -->"
        errors = lint.description_errors(body)
        self.assertEqual(len(errors), 2)

    def test_an_unchanged_template_line_is_not_prose(self):
        template = "## Summary\nDescribe the change in a sentence or two.\n"
        body = "## Summary\nDescribe the change in a sentence or two.\nCloses #963."
        errors = lint.description_errors(body, template=template)
        self.assertEqual(len(errors), 1)
        self.assertIn("unchanged from the template", errors[0])

    def test_headings_and_checklist_rows_are_not_prose(self):
        body = "## Summary\n### Detail\n- [ ] tested\n- [x] documented\nCloses #963."
        errors = lint.description_errors(body)
        self.assertEqual(len(errors), 1)
        self.assertIn("too short", errors[0])


class TheWorkflowUsesTheModule(unittest.TestCase):
    """The rules are only enforced if the workflow actually runs them."""

    def setUp(self):
        self.code = [
            line
            for line in (REPO_ROOT / ".github" / "workflows" / "pr-lint.yml")
            .read_text(encoding="utf-8")
            .splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]

    def test_the_script_is_invoked(self):
        self.assertIn(
            "run: python3 .github/scripts/pr_description_lint.py",
            [line.strip() for line in self.code],
        )

    def test_the_author_type_reaches_the_script(self):
        """Without `PR_AUTHOR_TYPE` the exemption is dead code and bots stay blocked.

        This is the wiring the unit tests above cannot see: `is_bot` can be
        perfect and still never be handed anything.
        """
        self.assertTrue(
            any(line.strip().startswith("PR_AUTHOR_TYPE:") for line in self.code),
            "the workflow does not pass the PR author's type to the script",
        )
        self.assertTrue(
            any("user.type" in line for line in self.code),
            "PR_AUTHOR_TYPE is set from something other than the payload's user.type",
        )

    def test_no_heredoc_copy_of_the_rules_remains(self):
        """Two copies of a rule is one copy that will drift."""
        self.assertFalse(
            [line for line in self.code if "MIN_PROSE" in line],
            "the workflow still carries an inline copy of the lint rules",
        )
