"""`keel init` — scaffold a default `.keel/project.yaml`, or build one with a wizard.

Pure + deterministic: :func:`detect_stack` is a function of which marker files exist,
:func:`render_config` renders YAML from explicit values, and :func:`wizard` builds those
values through an injectable `ask` callback (so the interactive flow is unit-tested
offline). The CLI supplies the real `input`-based `ask` and does the file I/O.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from . import consent
from . import yaml_helper as yaml

#: marker file (checked in order) -> stack name.
_MARKERS: tuple[tuple[str, str], ...] = (
    ("pubspec.yaml", "flutter"),
    ("build.gradle", "android"),
    ("build.gradle.kts", "android"),
    ("pom.xml", "java"),
    ("Cargo.toml", "rust"),
    ("go.mod", "go"),
    ("pyproject.toml", "python"),
    ("setup.py", "python"),
    ("requirements.txt", "python"),
    ("Pipfile", "python"),
    ("package.json", "node"),
)

#: per-stack defaults: platform, build cmd, lint cmd (or None), tier-3 globs.
_TEMPLATES: dict[str, dict] = {
    "flutter": {
        "platform": "flutter",
        "build": "flutter test",
        "lint": "flutter analyze",
        "globs": ("lib/**/*.dart",),
    },
    "python": {
        "platform": "python",
        "build": "make test",
        "lint": "ruff check .",
        "globs": ("src/**/*.py",),
    },
    "node": {
        "platform": "node",
        "build": "npm test",
        "lint": "npm run lint",
        "globs": ("src/**/*.ts", "src/**/*.js"),
    },
    "android": {
        "platform": "android",
        "build": "./gradlew test",
        "lint": "./gradlew lint",
        "globs": ("app/src/**",),
    },
    "rust": {
        "platform": "rust",
        "build": "cargo test",
        "lint": "cargo clippy",
        "globs": ("src/**/*.rs",),
    },
    "go": {
        "platform": "go",
        "build": "go test ./...",
        "lint": "golangci-lint run",
        "globs": ("**/*.go",),
    },
    "java": {
        "platform": "java",
        "build": "mvn test",
        "lint": "mvn checkstyle:check",
        "globs": ("src/main/**",),
    },
    "generic": {"platform": "generic", "build": "make test", "lint": None, "globs": ()},
}


def detect_stack(root: str | Path) -> str:
    """Detect the project stack from marker files (``generic`` if none match)."""
    root = Path(root)
    for marker, stack in _MARKERS:
        if (root / marker).exists():
            return stack
    return "generic"


def detect_base_branch(root: str | Path) -> str:
    """Detect the repository's default base branch (defaults to ``main``)."""
    root = Path(root)
    head_file = root / ".git" / "HEAD"
    if head_file.exists():
        try:
            content = head_file.read_text(encoding="utf-8").strip()
            if content.startswith("ref: refs/heads/"):
                ref_name = content[len("ref: refs/heads/") :].strip()
                if ref_name in ("main", "master", "develop", "trunk"):
                    return ref_name
        except OSError:
            return "main"
    return "main"


def auto_detect_config(
    root: str | Path,
    *,
    repo: str = "my-repo",
) -> tuple[str, dict]:
    """Inspect the repository stack and base branch, returning (yaml_text, metadata)."""
    root = Path(root)
    stack = detect_stack(root)
    base_branch = detect_base_branch(root)
    t = _TEMPLATES.get(stack, _TEMPLATES["generic"])
    meta = {
        "stack": stack,
        "platform": t["platform"],
        "base_branch": base_branch,
        "build_cmd": t["build"],
        "lint_cmd": t["lint"],
        "tier3_globs": t["globs"],
    }
    text = render_config(
        repo=repo,
        base_branch=base_branch,
        platform=t["platform"],
        build_cmd=t["build"],
        lint_cmd=t["lint"],
        tier3_globs=t["globs"],
        generator="keel init --auto",
    )
    return text, meta


def render_config(
    *,
    repo: str = "my-repo",
    base_branch: str = "main",
    platform: str = "generic",
    build_cmd: str = "make test",
    lint_cmd: str | None = None,
    tier3_globs: tuple[str, ...] = (),
    timezone: str | None = None,
    merge_window: str | None = None,
    consent_mode: str = "explicit",
    generator: str = "keel init",
) -> str:
    """Render a valid ``project.yaml`` from explicit values (passes ``keel validate``)."""
    if consent_mode not in consent.CONSENT_MODES:
        raise ValueError(
            f"unknown consent mode {consent_mode!r}; valid: {', '.join(consent.CONSENT_MODES)}"
        )
    generator_comment = " ".join(str(generator).splitlines())
    lines = [
        f"# keel consumer config (generated by `{generator_comment}`)",
        "extends: keel",
        'core_version: "^1.0"',
        f"repo: {_yaml_scalar(repo)}",
        f"base_branch: {_yaml_scalar(base_branch)}",
        f"platform: {_yaml_scalar(platform)}",
        f"consent_mode: {_yaml_scalar(consent_mode)}",
    ]
    if timezone:
        lines.append(f"timezone: {_yaml_scalar(timezone)}")
    if merge_window:
        lines.append(f"merge_window: {_yaml_scalar(merge_window)}")
    lines += ["", "knobs:", f"  build_gate_cmd: {_yaml_scalar(build_cmd)}"]
    if lint_cmd:
        lines.append(f"  lint_cmd: {_yaml_scalar(lint_cmd)}")
    if tier3_globs:
        lines.append("  tier3_globs:")
        lines += [f"    - {_yaml_scalar(g)}" for g in tier3_globs]
    gates = "[build, lint]" if lint_cmd else "[build]"
    lines += ["", f"gates: {gates}", "extensions: {}", "extensions_dir: .keel/extensions", ""]
    return "\n".join(lines)


def _yaml_scalar(value: str) -> str:
    """Render a scalar as inline YAML so scaffolded values cannot inject new keys."""
    return yaml.dump(
        str(value),
        default_style='"',
        default_flow_style=True,
        width=10**6,
        sort_keys=False,
    ).strip()


def default_config(stack: str, *, repo: str = "my-repo", base_branch: str = "main") -> str:
    """Render the default ``project.yaml`` for ``stack`` (non-interactive)."""
    t = _TEMPLATES.get(stack, _TEMPLATES["generic"])
    return render_config(
        repo=repo,
        base_branch=base_branch,
        platform=t["platform"],
        build_cmd=t["build"],
        lint_cmd=t["lint"],
        tier3_globs=t["globs"],
    )


def wizard(stack: str, ask: Callable[[str, str], str], *, repo: str = "my-repo") -> str:
    """Build a config by asking for each value, defaulting to the stack template.

    ``ask(prompt, default)`` returns the chosen value (an empty answer ⇒ the default).
    Pure given ``ask`` — the CLI passes a real `input`-based implementation.
    """
    t = _TEMPLATES.get(stack, _TEMPLATES["generic"])
    base = ask("Base branch", "main")
    tz = ask("Timezone (IANA, blank to skip)", "Europe/Istanbul")
    win = ask("Merge window HH:MM-HH:MM (blank to skip)", "07:00-01:30")
    mode = ask("Consent mode (explicit, standing, agent)", "explicit") or "explicit"
    build = ask("Build/test command", t["build"])
    lint = ask("Lint command (blank to skip)", t["lint"] or "")
    return render_config(
        repo=repo,
        base_branch=base,
        platform=t["platform"],
        build_cmd=build,
        lint_cmd=lint or None,
        tier3_globs=t["globs"],
        timezone=tz or None,
        merge_window=win or None,
        consent_mode=mode,
        generator="keel init --wizard",
    )
