"""`keel init` — scaffold a default `.keel/project.yaml`, or build one with a wizard.

Pure + deterministic: :func:`detect_stack` is a function of which marker files exist,
:func:`render_config` renders YAML from explicit values, and :func:`wizard` builds those
values through an injectable `ask` callback (so the interactive flow is unit-tested
offline). The CLI supplies the real `input`-based `ask` and does the file I/O.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

#: marker file (checked in order) -> stack name.
_MARKERS: tuple[tuple[str, str], ...] = (
    ("pubspec.yaml", "flutter"),
    ("build.gradle", "android"),
    ("build.gradle.kts", "android"),
    ("pyproject.toml", "python"),
    ("setup.py", "python"),
    ("package.json", "node"),
)

#: per-stack defaults: platform, build cmd, lint cmd (or None), tier-3 globs.
_TEMPLATES: dict[str, dict] = {
    "flutter": {"platform": "flutter", "build": "flutter test", "lint": "flutter analyze",
                "globs": ("lib/**/*.dart",)},
    "python": {"platform": "python", "build": "make test", "lint": "ruff check .",
               "globs": ("src/**/*.py",)},
    "node": {"platform": "node", "build": "npm test", "lint": "npm run lint",
             "globs": ("src/**/*.ts", "src/**/*.js")},
    "android": {"platform": "android", "build": "./gradlew test", "lint": "./gradlew lint",
                "globs": ("app/src/**",)},
    "generic": {"platform": "generic", "build": "make test", "lint": None, "globs": ()},
}


def detect_stack(root: str | Path) -> str:
    """Detect the project stack from marker files (``generic`` if none match)."""
    root = Path(root)
    for marker, stack in _MARKERS:
        if (root / marker).exists():
            return stack
    return "generic"


def render_config(
    *, repo: str = "my-repo", base_branch: str = "main", platform: str = "generic",
    build_cmd: str = "make test", lint_cmd: str | None = None,
    tier3_globs: tuple[str, ...] = (), timezone: str | None = None,
    merge_window: str | None = None, generator: str = "keel init",
) -> str:
    """Render a valid ``project.yaml`` from explicit values (passes ``keel validate``)."""
    lines = [
        f"# keel consumer config (generated by `{generator}`)",
        "extends: keel",
        'core_version: "^0.4"',
        f"repo: {repo}",
        f"base_branch: {base_branch}",
        f"platform: {platform}",
    ]
    if timezone:
        lines.append(f"timezone: {timezone}")
    if merge_window:
        lines.append(f'merge_window: "{merge_window}"')
    lines += ["", "knobs:", f'  build_gate_cmd: "{build_cmd}"']
    if lint_cmd:
        lines.append(f'  lint_cmd: "{lint_cmd}"')
    if tier3_globs:
        lines.append("  tier3_globs:")
        lines += [f'    - "{g}"' for g in tier3_globs]
    gates = "[build, lint]" if lint_cmd else "[build]"
    lines += ["", f"gates: {gates}", "extensions: {}", "extensions_dir: .keel/extensions", ""]
    return "\n".join(lines)


def default_config(stack: str, *, repo: str = "my-repo", base_branch: str = "main") -> str:
    """Render the default ``project.yaml`` for ``stack`` (non-interactive)."""
    t = _TEMPLATES.get(stack, _TEMPLATES["generic"])
    return render_config(repo=repo, base_branch=base_branch, platform=t["platform"],
                         build_cmd=t["build"], lint_cmd=t["lint"], tier3_globs=t["globs"])


def wizard(stack: str, ask: Callable[[str, str], str], *, repo: str = "my-repo") -> str:
    """Build a config by asking for each value, defaulting to the stack template.

    ``ask(prompt, default)`` returns the chosen value (an empty answer ⇒ the default).
    Pure given ``ask`` — the CLI passes a real `input`-based implementation.
    """
    t = _TEMPLATES.get(stack, _TEMPLATES["generic"])
    base = ask("Base branch", "main")
    tz = ask("Timezone (IANA, blank to skip)", "Europe/Istanbul")
    win = ask("Merge window HH:MM-HH:MM (blank to skip)", "07:00-01:30")
    build = ask("Build/test command", t["build"])
    lint = ask("Lint command (blank to skip)", t["lint"] or "")
    return render_config(
        repo=repo, base_branch=base, platform=t["platform"], build_cmd=build,
        lint_cmd=lint or None, tier3_globs=t["globs"],
        timezone=tz or None, merge_window=win or None, generator="keel init --wizard",
    )
