"""`keel init` — detect a project's stack and scaffold a default ``.keel/project.yaml``.

Pure + deterministic: :func:`detect_stack` is a function of which marker files exist,
and :func:`default_config` renders a fixed template per stack. The CLI does the I/O.
"""

from __future__ import annotations

from pathlib import Path

#: marker file (checked in order) -> stack name.
_MARKERS: tuple[tuple[str, str], ...] = (
    ("pubspec.yaml", "flutter"),
    ("build.gradle", "android"),
    ("build.gradle.kts", "android"),
    ("pyproject.toml", "python"),
    ("setup.py", "python"),
    ("package.json", "node"),
)

#: per-stack template: platform, build cmd, lint cmd (or None), tier-3 globs.
_TEMPLATES: dict[str, dict] = {
    "flutter": {"platform": "flutter", "build": "flutter test", "lint": "flutter analyze",
                "globs": ("lib/**/*.dart",)},
    "python": {"platform": "python", "build": "make test", "lint": "ruff check .",
               "globs": ("src/**/*.py",)},
    "node": {"platform": "node", "build": "npm test", "lint": "npm run lint",
             "globs": ("src/**/*.ts", "src/**/*.js")},
    "android": {"platform": "android", "build": "./gradlew test", "lint": "./gradlew lint",
                "globs": ("app/src/**",)},
    "generic": {"platform": "generic", "build": "make test", "lint": None, "globs": ()},
}


def detect_stack(root: str | Path) -> str:
    """Detect the project stack from marker files (``generic`` if none match)."""
    root = Path(root)
    for marker, stack in _MARKERS:
        if (root / marker).exists():
            return stack
    return "generic"


def default_config(stack: str, *, repo: str = "my-repo", base_branch: str = "main") -> str:
    """Render a valid default ``project.yaml`` for ``stack`` (passes ``keel validate``)."""
    t = _TEMPLATES.get(stack, _TEMPLATES["generic"])
    lines = [
        "# keel consumer config (generated by `keel init`)",
        "extends: keel",
        'core_version: "^0.1"',
        f"repo: {repo}",
        f"base_branch: {base_branch}",
        f"platform: {t['platform']}",
        "",
        "knobs:",
        f'  build_gate_cmd: "{t["build"]}"',
    ]
    if t["lint"]:
        lines.append(f'  lint_cmd: "{t["lint"]}"')
    if t["globs"]:
        lines.append("  tier3_globs:")
        lines += [f'    - "{g}"' for g in t["globs"]]
    gates = "[build, lint]" if t["lint"] else "[build]"
    lines += ["", f"gates: {gates}", "extensions: {}", "extensions_dir: .keel/extensions", ""]
    return "\n".join(lines)
