"""keel runtime workspace: the ``.keel`` directory, its gitignore, and scratch.

Keel writes runtime artifacts (checkpoints, activity records, the run ledger,
merge locks) and its agentic steps stage transient scratch (PR diffs, issue
dumps, draft review/closure prose) while driving a workflow. None of this
belongs in the consumer's primary checkout: it is keel-owned, disposable
runtime state. This module owns the one place those artifacts live — the
project's ``.keel`` directory — and keeps them out of ``git status`` by
scaffolding a ``.keel/.gitignore`` that ignores the runtime subtrees while
leaving committed config (``project.yaml``) and extensions tracked.

It also exposes the **scratch directory** (``.keel/scratch``): the sanctioned
place for any ad-hoc transient file an agent needs to stage. Routing scratch
here — instead of the repo root — is why a consumer no longer sees
``plan.json``, ``pr_<n>.diff``, ``issue.md`` and friends accumulate in their
checkout.

Pure-core + thin I/O, mirroring :mod:`keel.checkpoint` and :mod:`keel.activity`:
:func:`runtime_gitignore_body` is a deterministic pure function; only
:func:`ensure_runtime_gitignore`, :func:`ensure_runtime_gitignore_for` and
:func:`scratch_dir` touch the filesystem.
"""

from __future__ import annotations

from pathlib import Path

KEEL_DIRNAME = ".keel"
GITIGNORE_NAME = ".gitignore"
SCRATCH_DIRNAME = "scratch"

# Runtime subtrees of ``.keel`` that are disposable per-run state, expressed as
# patterns relative to the ``.keel/.gitignore`` that lists them. ``project.yaml``
# and ``extensions/`` are intentionally absent: they are committed config.
RUNTIME_IGNORE_ENTRIES: tuple[str, ...] = ("state/", "activity/", "scratch/", "*.tmp")

_GITIGNORE_HEADER = (
    "# keel runtime artifacts — generated by `keel`; commit this file.",
    "# These subtrees are disposable per-run state (checkpoints, activity,",
    "# locks, agent scratch); keeping them ignored stops keel from polluting",
    "# your checkout. Delete an entry only if you deliberately track that path.",
)


def keel_dir(root: str | Path = ".") -> Path:
    """Return the project's ``.keel`` directory under ``root`` (not created)."""
    return Path(root) / KEEL_DIRNAME


def runtime_gitignore_body() -> str:
    """Return the canonical ``.keel/.gitignore`` body (deterministic)."""
    lines = [*_GITIGNORE_HEADER, *RUNTIME_IGNORE_ENTRIES]
    return "\n".join(lines) + "\n"


def ensure_runtime_gitignore(keel_directory: str | Path) -> bool:
    """Scaffold or top up ``<keel_directory>/.gitignore``; idempotent.

    Creates the gitignore with the canonical body when absent. When it already
    exists, appends only the runtime entries that are missing — preserving any
    operator additions and never rewriting an already-complete file. Returns
    ``True`` when the file was created or changed, ``False`` when it was already
    a superset of the runtime entries (or the ``.keel`` directory is absent).
    """
    directory = Path(keel_directory)
    if not directory.is_dir():
        return False
    gitignore = directory / GITIGNORE_NAME
    if not gitignore.exists():
        gitignore.write_text(runtime_gitignore_body(), encoding="utf-8")
        return True
    existing = gitignore.read_text(encoding="utf-8")
    present = {line.strip() for line in existing.splitlines()}
    missing = [entry for entry in RUNTIME_IGNORE_ENTRIES if entry not in present]
    if not missing:
        return False
    prefix = existing if existing.endswith("\n") or existing == "" else existing + "\n"
    gitignore.write_text(prefix + "\n".join(missing) + "\n", encoding="utf-8")
    return True


def ensure_runtime_gitignore_for(artifact_path: str | Path) -> bool:
    """Self-heal the gitignore for a runtime artifact about to be written.

    Walks the artifact's ancestors for a ``.keel`` directory and scaffolds its
    gitignore. A no-op (returns ``False``) when the artifact lives outside any
    ``.keel`` tree — e.g. an operator pointed an output path elsewhere on
    purpose, which keel must not silently ignore.
    """
    target = Path(artifact_path)
    for ancestor in target.parents:
        if ancestor.name == KEEL_DIRNAME and ancestor.is_dir():
            return ensure_runtime_gitignore(ancestor)
    return False


def scratch_dir(root: str | Path = ".", *, create: bool = True) -> Path:
    """Return ``.keel/scratch`` — the sanctioned home for transient artifacts.

    With ``create`` (the default) the directory and the runtime gitignore are
    materialised so callers can write into it immediately and it never surfaces
    in ``git status``.
    """
    directory = keel_dir(root)
    scratch = directory / SCRATCH_DIRNAME
    if create:
        scratch.mkdir(parents=True, exist_ok=True)
        ensure_runtime_gitignore(directory)
    return scratch
