"""keel runtime workspace: the ``.keel`` directory, its gitignore, and scratch.

Keel writes runtime artifacts (checkpoints, activity records, the run ledger,
merge locks) and its agentic steps stage transient scratch (PR diffs, issue
dumps, draft review/closure prose) while driving a workflow. None of this
belongs in the consumer's primary checkout: it is keel-owned, disposable
runtime state. This module owns the one place those artifacts live - the
project's ``.keel`` directory - and keeps them out of ``git status`` by
scaffolding a ``.keel/.gitignore`` that ignores the runtime subtrees while
leaving committed config (``project.yaml``) and extensions tracked.

It also exposes the **scratch directory** (``.keel/scratch``): the sanctioned
place for any ad-hoc transient file an agent needs to stage. Routing scratch
here - instead of the repo root - is why a consumer no longer sees
``plan.json``, ``pr_<n>.diff``, ``issue.md`` and friends accumulate in their
checkout.

Finally it owns **reclamation** of the disposable runtime trees so they do not
grow without bound: :func:`clean_scratch` empties ``.keel/scratch`` and
:func:`prune_activity` applies count-based retention to ``.keel/activity``.
Reclamation is deliberately scoped to those two trees - it never touches the
run ledger, checkpoint, or locks, which have their own bounded lifecycles and
(for the ledger) are durable by design.

Pure-core + thin I/O, mirroring :mod:`keel.checkpoint` and :mod:`keel.activity`:
:func:`runtime_gitignore_body` is a deterministic pure function; only the
``ensure_*``, :func:`scratch_dir`, and the reclamation helpers touch the
filesystem.
"""

from __future__ import annotations

import contextlib
import os
import shutil
import tempfile
from pathlib import Path

KEEL_DIRNAME = ".keel"
GITIGNORE_NAME = ".gitignore"
SCRATCH_DIRNAME = "scratch"

# Runtime subtrees of ``.keel`` that are disposable per-run state, expressed as
# patterns relative to the ``.keel/.gitignore`` that lists them. ``project.yaml``
# and ``extensions/`` are intentionally absent: they are committed config.
#
# ``/worktrees/`` is where ``keel swarm`` checks out one isolated tree per cluster
# (``swarm_runtime.build_worktree_path``). A parallel run leaves a full working
# copy per worker there, so without this entry a swarm turns ``git status`` into
# hundreds of untracked files — and the operator's habit of trusting a clean
# status is the thing that notices a real stray file (#877).
#
# Anchored with a leading slash, unlike its neighbours. An unanchored
# ``worktrees/`` matches at any depth, including
# ``.keel/extensions/<ext>/worktrees/`` — and ``extensions/`` is committed config,
# deliberately absent from this list. A third-party extension is far likelier to
# contain a directory called ``worktrees`` than one called ``scratch``, so the
# looseness that is theoretical for the others is not for this one.
RUNTIME_IGNORE_ENTRIES: tuple[str, ...] = (
    "state/",
    "activity/",
    "scratch/",
    "/worktrees/",
    "*.tmp",
)

_GITIGNORE_HEADER = (
    "# keel runtime artifacts - generated by `keel`; commit this file.",
    "# These subtrees are disposable per-run state (checkpoints, activity,",
    "# locks, agent scratch); keeping them ignored stops keel from polluting",
    "# your checkout. Delete an entry only if you deliberately track that path.",
)


def keel_dir(root: str | Path = ".") -> Path:
    """Return the project's ``.keel`` directory under ``root`` (not created)."""
    return Path(root) / KEEL_DIRNAME


def runtime_gitignore_body() -> str:
    """Return the canonical ``.keel/.gitignore`` body (deterministic)."""
    lines = [*_GITIGNORE_HEADER, *RUNTIME_IGNORE_ENTRIES]
    return "\n".join(lines) + "\n"


def ensure_runtime_gitignore(keel_directory: str | Path) -> bool:
    """Scaffold or top up ``<keel_directory>/.gitignore``; idempotent.

    Creates the gitignore with the canonical body when absent. When it already
    exists, appends only the runtime entries that are missing - preserving any
    operator additions and never rewriting an already-complete file. Returns
    ``True`` when the file was created or changed, ``False`` when it was already
    a superset of the runtime entries (or the ``.keel`` directory is absent).
    """
    directory = Path(keel_directory)
    if not directory.is_dir():
        return False
    gitignore = directory / GITIGNORE_NAME
    if not gitignore.exists():
        gitignore.write_text(runtime_gitignore_body(), encoding="utf-8")
        return True
    existing = gitignore.read_text(encoding="utf-8")
    present = {line.strip() for line in existing.splitlines()}
    missing = [entry for entry in RUNTIME_IGNORE_ENTRIES if entry not in present]
    if not missing:
        return False
    prefix = existing if existing.endswith("\n") or existing == "" else existing + "\n"
    gitignore.write_text(prefix + "\n".join(missing) + "\n", encoding="utf-8")
    return True


def ensure_runtime_gitignore_for(artifact_path: str | Path) -> bool:
    """Self-heal the gitignore for a runtime artifact about to be written.

    Walks the artifact's ancestors for a ``.keel`` directory and scaffolds its
    gitignore. A no-op (returns ``False``) when the artifact lives outside any
    ``.keel`` tree - e.g. an operator pointed an output path elsewhere on
    purpose, which keel must not silently ignore.
    """
    target = Path(artifact_path)
    for ancestor in target.parents:
        if ancestor.name == KEEL_DIRNAME and ancestor.is_dir():
            return ensure_runtime_gitignore(ancestor)
    return False


def write_text_atomic(path: str | Path, content: str, *, encoding: str = "utf-8") -> None:
    """Write ``content`` to ``path`` atomically **and durably**.

    One writer for every runtime artifact that must survive a crash mid-write:
    the checkpoint, activity records, and swarm run state. Each had its own copy
    of the temp-file-and-rename dance, which is how the third one
    (:func:`keel.swarm.save_swarm_state`) was still a bare ``write_text`` — a
    torn file on interruption, the exact bug class #872 was filed about (#932).

    ``os.replace`` makes the *swap* atomic: a reader sees the old file or the new
    one, never a partial. It does not make the new bytes **durable** — after a
    power loss the rename can survive with the file's contents still in the page
    cache. #872's own Impact section named that scenario and only the atomicity
    half shipped, so the data is fsynced before the rename and the directory
    entry after it.

    The directory fsync is best-effort: Windows cannot open a directory with
    ``os.open``, and there the rename's durability is the filesystem's business
    rather than something this call can request. Failing the write over it would
    trade a real guarantee on POSIX for a broken one everywhere.
    """
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    ensure_runtime_gitignore_for(target)
    fd, temp_file = tempfile.mkstemp(prefix=f".{target.name}.", dir=target.parent, text=True)
    try:
        with os.fdopen(fd, "w", encoding=encoding) as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_file, target)
    except Exception:
        with contextlib.suppress(OSError):
            os.unlink(temp_file)
        raise
    _fsync_directory(target.parent)


def _fsync_directory(directory: Path) -> bool:
    """Flush a directory entry so a completed rename survives a power loss.

    Best-effort, and its own function so the success path is reachable by a test
    on every platform: Windows cannot ``os.open`` a directory, so leaving this
    inline left three lines uncovered there and dropped the Windows coverage run
    below the 100% bar — a real failure hidden behind #953's masked job.

    Returns whether the sync happened, so a caller (today only a test) can tell
    "flushed" from "this platform would not let us ask".
    """
    try:
        dir_fd = os.open(directory, os.O_RDONLY)
    except OSError:
        return False
    try:
        os.fsync(dir_fd)
    finally:
        os.close(dir_fd)
    return True


def scratch_dir(root: str | Path = ".", *, create: bool = True) -> Path:
    """Return ``.keel/scratch`` - the sanctioned home for transient artifacts.

    With ``create`` (the default) the directory and the runtime gitignore are
    materialised so callers can write into it immediately and it never surfaces
    in ``git status``.
    """
    directory = keel_dir(root)
    scratch = directory / SCRATCH_DIRNAME
    if create:
        scratch.mkdir(parents=True, exist_ok=True)
        ensure_runtime_gitignore(directory)
    return scratch


def scratch_entries(root: str | Path = ".") -> list[str]:
    """Sorted top-level names currently under ``.keel/scratch`` (``[]`` if none)."""
    scratch = keel_dir(root) / SCRATCH_DIRNAME
    if not scratch.is_dir():
        return []
    return sorted(p.name for p in scratch.iterdir())


def clean_scratch(root: str | Path = ".") -> list[str]:
    """Empty ``.keel/scratch`` contents; return the entries that were removed.

    Scratch is transient by definition, so this empties its contents while
    keeping the directory node intact. A no-op (``[]``) when scratch does not exist.
    """
    entries = scratch_entries(root)
    scratch = keel_dir(root) / SCRATCH_DIRNAME
    if scratch.is_dir():
        for child in scratch.iterdir():
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink(missing_ok=True)
    return entries


def activity_prune_plan(activity_dir: str | Path, *, keep_last: int) -> list[str]:
    """Names of activity records that exceed ``keep_last`` (oldest first removed).

    Retention is count-based: the newest ``keep_last`` ``.json`` records (by
    mtime, then name for a stable tiebreak) are kept; the rest are returned as
    the prune plan. Only ``.json`` files are considered, so a stray file never
    counts against - or gets caught by - retention. ``keep_last`` must be
    non-negative. A no-op (``[]``) when the directory is absent or within budget.
    """
    if keep_last < 0:
        raise ValueError("keep_last must be non-negative")
    directory = Path(activity_dir)
    if not directory.is_dir():
        return []
    records = [p for p in directory.iterdir() if p.is_file() and p.suffix == ".json"]
    if len(records) <= keep_last:
        return []
    ordered = sorted(records, key=lambda p: (p.stat().st_mtime, p.name), reverse=True)
    return sorted(p.name for p in ordered[keep_last:])


def prune_activity(activity_dir: str | Path, *, keep_last: int) -> list[str]:
    """Apply count-based retention to ``activity_dir``; return the names removed.

    Removes exactly the records named by :func:`activity_prune_plan`. Never
    touches non-``.json`` entries, and is only ever pointed at the activity
    directory - the run ledger, checkpoint, and locks live elsewhere and are
    out of reach by construction.
    """
    directory = Path(activity_dir)
    doomed = activity_prune_plan(directory, keep_last=keep_last)
    for name in doomed:
        (directory / name).unlink()
    return doomed
