#!/usr/bin/env python3
"""Bump keel's version across every file a release must touch.

The version string lives in more places than is obvious, and two of them are
easy to miss by hand (they bit the 1.7.0 release):

- ``.claude-plugin/plugin.json`` and ``.codex-plugin/plugin.json`` — *not*
  regenerated by ``make plugin``; a stale value fails
  ``test_plugin_manifest_version_matches_keel_version`` (Claude) or
  ``test_codex_plugin_manifest_version_matches_keel_version`` (Codex).
- every adapter surface embeds a ``keel_version=<v>`` marker, so the surfaces
  must be regenerated (``make plugin`` + ``make adapters``) after a bump or the
  drift test fails.

This script rewrites the *string* sources deterministically; the ``make
release-bump`` target runs it and then regenerates the surfaces. It deliberately
edits keel-repo-specific paths — it is a maintenance tool (sibling to
``release_smoke.py``), not a consumer-neutral ``keel`` CLI command.

Prose that merely *names* a version (e.g. "Since **1.6.5**", a dated release-history
line) is left untouched. What is rewritten is the declared version assignments, plus —
in the site files only — the pinned-install (``keel@vX.Y.Z``) and the badge behind a
``data-version`` / ``version:`` anchor.

Note the site rewrites match by *shape*, not against the current version, so they widen
what the old literal edits could reach: a deliberate historical pin written as
``keel@v1.6.5`` inside ``index.html`` or ``content.js`` would now be rewritten too. That
is the deliberate trade for re-syncing a file that has already fallen behind — see
:data:`_SITE_PATTERNS`. Keep historical pins out of those two files, or in a form other
than ``keel@vX.Y.Z``.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# `scripts/` is a directory of maintenance tools, not an installed package, so a
# sibling import needs the directory on the path. Already true when this file is
# run directly (`python scripts/release_bump.py`); stated here so importing it
# from a test works the same way.
_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from release_surfaces import literal_surfaces, shape_surfaces  # noqa: E402

SEMVER = re.compile(r"^\d+\.\d+\.\d+$")

# Repo root = parent of this script's directory (scripts/..).
DEFAULT_ROOT = Path(__file__).resolve().parent.parent


def current_version(root: Path) -> str:
    """Read the declared version from ``pyproject.toml``."""
    text = (root / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version = "([^"]+)"', text, re.MULTILINE)
    if not match:
        raise ValueError('could not find `version = "..."` in pyproject.toml')
    return match.group(1)


#: keel-visual is a second distribution in this repo on its own version line and
#: its own tag namespace, so it cannot ride core's bump. Its runbook said "edit
#: keel-visual/pyproject.toml" and nothing else, which left ``__version__`` at
#: 0.6.0 through the 0.7.0 and 0.8.0 releases (#796). Both files are listed here
#: so the pair moves together; the test in test_release_docs.py is what makes a
#: future omission fail rather than ship.
#: ``(path, regex)``, where the regex is a **three-group sandwich**:
#: ``(prefix)(version)(suffix)``. ``bump_visual`` substitutes ``\g<1>{new}\g<3>``,
#: so group 2 is the version and the two anchors around it are what keep the
#: rewrite off prose that happens to contain the same digits — the pattern matches
#: more than the version, and replaces only the middle.
#:
#: That shape is a contract, not an implementation detail: ``release_check.py``
#: reads this same list rather than restating it, and takes group 2 as the version.
#: A two-group pattern added here would make the guard compare the wrong substring,
#: so it asserts the group count (``VISUAL_PATTERN_GROUPS``) instead of trusting it.
VISUAL_EDITS = (
    ("keel-visual/pyproject.toml", re.compile(r'(?m)^(version = ")([^"]+)(")')),
    (
        "keel-visual/src/keel_visual/__init__.py",
        re.compile(r'(?m)^(__version__ = ")([^"]+)(")'),
    ),
)
VISUAL_PYPROJECT = VISUAL_EDITS[0][0]


def visual_version(root: Path) -> str:
    """Read keel-visual's declared version from its own ``pyproject.toml``."""
    text = (root / VISUAL_PYPROJECT).read_text(encoding="utf-8")
    match = VISUAL_EDITS[0][1].search(text)
    if not match:
        raise ValueError(f'could not find `version = "..."` in {VISUAL_PYPROJECT}')
    return match.group(2)


def visual_divergence(root: Path) -> str | None:
    """Warn when keel-visual's own two version markers disagree.

    ``keel-visual/pyproject.toml`` is the declared ("core") version for the
    package; ``keel_visual/__init__.py``'s ``__version__`` is a derived marker
    that only ``bump_visual`` keeps in lockstep with it. A *core* bump
    (``--package core``, the default) never calls ``bump_visual`` — it does not
    touch keel-visual at all — so if the pair had already drifted apart (the
    #796 shape: ``__version__`` left at ``0.6.0`` for two releases while
    ``pyproject.toml`` moved on to 0.8.0), a plain core release ships right past
    it, unnoticed, because nothing about bumping core looks at keel-visual.

    Returns ``None`` when the pair agrees, or when keel-visual is not present
    under ``root`` (a fixture tree, or a checkout without the second package).
    """
    if not (root / VISUAL_PYPROJECT).exists():
        return None
    try:
        declared = visual_version(root)
    except ValueError:
        return None
    marker_rel, marker_pattern = VISUAL_EDITS[1]
    marker_path = root / marker_rel
    if not marker_path.exists():
        return None
    match = marker_pattern.search(marker_path.read_text(encoding="utf-8"))
    if not match:
        return None
    marker = match.group(2)
    if marker == declared:
        return None
    return (
        f"keel-visual's version markers have diverged from each other: "
        f"{VISUAL_PYPROJECT} declares {declared}, {marker_rel} carries {marker} — "
        f"run `scripts/release_bump.py {declared} --package keel-visual` to repair."
    )


def bump_visual(root: Path, new: str) -> tuple[str, list[str]]:
    """Rewrite keel-visual's version to ``new``. Returns ``(old, changed)``.

    Re-running at the current version is a supported repair, not a no-op — the
    same property ``bump`` has, and the one that matters here: when only one of
    the two files has drifted, re-running at the declared version fixes the other.
    """
    if not SEMVER.match(new):
        raise ValueError(f"version must be X.Y.Z, got {new!r}")
    old = visual_version(root)
    changed: list[str] = []
    for rel, pattern in VISUAL_EDITS:
        path = root / rel
        text = path.read_text(encoding="utf-8")
        rewritten = pattern.sub(rf"\g<1>{new}\g<3>", text)
        if rewritten != text:
            path.write_text(rewritten, encoding="utf-8")
            changed.append(rel)
    return old, changed


def _edits(old: str, new: str) -> list[tuple[str, str, str]]:
    """Return ``(relative_path, find, replace)`` rewrites for ``old`` → ``new``.

    Derived from :data:`release_surfaces.RELEASE_SURFACES` rather than restated
    here. That table is also what ``scripts/release_check.py`` asserts against, so
    a surface registered for the bump is guarded at tag time by the same edit —
    the half-registration that left three site files behind for seven releases is
    no longer expressible.

    Each ``find`` is specific enough that only the version-bearing token is
    touched — never historical prose that happens to mention ``old``.
    """
    return [
        (surface.path, surface.token.format(version=old), surface.token.format(version=new))
        for surface in literal_surfaces()
    ]


#: Version-bearing tokens in the site, matched by *pattern* rather than by the
#: current version.
#:
#: Two gaps this closes, with one symptom. ``docs.html``, ``coverage.html`` and
#: ``content.js`` were never in ``_edits`` at all — the runbook named them as a manual
#: step, and the step was missed for seven releases. ``index.html`` *was* listed, but the
#: literal edits find ``old`` (read from ``pyproject.toml``), so a file that has already
#: fallen behind contains neither ``old`` nor ``new``, is skipped by the ``find not in
#: text`` guard, and stays behind forever. Matching by shape registers the three missing
#: surfaces and removes that fragility from the fourth at the same time.
#:
#: Projected from the shared table in ``release_surfaces.py`` — see there for why the
#: two rewrite modes differ and what a historical pin must not look like in these files.
_SITE_PATTERNS: tuple[tuple[str, str, str], ...] = tuple(
    (surface.path, surface.pattern, surface.token.replace("{version}", "{new}"))
    for surface in shape_surfaces()
)


def bump(root: Path, new: str) -> tuple[str, list[str]]:
    """Rewrite the version to ``new`` across the release files under ``root``.

    Returns ``(old_version, changed_relative_paths)``. A file whose ``find``
    token is absent is skipped (so re-running after a partial bump is safe).

    Re-running at the *current* version is a supported repair, not a no-op: the site
    rewrites still run. That is exactly the recovery an operator reaches for when the
    drift test fires, or after a bump that died between the ``pyproject.toml`` write —
    the first literal edit — and the site loop. The literal edits are skipped in that
    case because ``old == new`` makes each ``find`` a no-op anyway.
    """
    if not SEMVER.match(new):
        raise ValueError(f"version must be X.Y.Z, got {new!r}")
    old = current_version(root)
    changed: list[str] = []
    if old != new:
        for rel, find, replace in _edits(old, new):
            path = root / rel
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8")
            if find not in text:
                continue
            path.write_text(text.replace(find, replace), encoding="utf-8")
            if rel not in changed:
                changed.append(rel)
    for rel, pattern, template in _SITE_PATTERNS:
        path = root / rel
        if not path.exists():
            continue  # a checkout without the site (or a fixture root) is not an error
        text = path.read_text(encoding="utf-8")
        rewritten = re.sub(pattern, template.format(new=new), text)
        if rewritten == text:
            continue
        path.write_text(rewritten, encoding="utf-8")
        if rel not in changed:
            changed.append(rel)
    return old, changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Bump keel's release version.")
    parser.add_argument("version", help="new version, X.Y.Z")
    parser.add_argument(
        "--root", default=str(DEFAULT_ROOT), help="repo root (defaults to the keel checkout)"
    )
    parser.add_argument(
        "--package",
        choices=("core", "keel-visual"),
        default="core",
        help="which distribution to bump; keel-visual is on its own version line",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help=(
            "exit 1 if keel-visual's version markers have diverged from each other "
            "(default: warn and continue)"
        ),
    )
    args = parser.parse_args(argv)

    root = Path(args.root)

    if args.package == "core":
        # A core bump never touches keel-visual, so a pre-existing drift between
        # its own two markers (#796) would otherwise ship unnoticed. Checked
        # before any file is written, so a --strict refusal leaves the tree
        # untouched rather than half-bumped.
        warning = visual_divergence(root)
        if warning:
            print(f"warning: {warning}", file=sys.stderr)
            if args.strict:
                print("release-bump failed: keel-visual left behind (--strict)", file=sys.stderr)
                return 1

    try:
        if args.package == "keel-visual":
            old, changed = bump_visual(root, args.version)
        else:
            old, changed = bump(root, args.version)
    except (ValueError, OSError) as exc:
        print(f"release-bump failed: {exc}", file=sys.stderr)
        return 1

    if not changed:
        print(f"release-bump: already at {args.version}; nothing to change")
        return 0

    if old == args.version:
        print(f"release-bump: already at {args.version}; re-synced files that had drifted")
    else:
        print(f"release-bump: {old} -> {args.version}")
    for rel in changed:
        print(f"  updated {rel}")
    if args.package == "keel-visual":
        # Core's next steps do not apply: keel-visual has no generated adapter
        # surfaces, its own CHANGELOG, and its own tag namespace. Printing core's
        # runbook here would be a wrong instruction, which is how #796 started.
        print(
            "Next: add a keel-visual/CHANGELOG.md entry, then follow "
            "keel-visual/RELEASING.md to tag `keel-visual-vX.Y.Z`."
        )
    else:
        print(
            "Next: `make plugin && make adapters` (regenerate keel_version markers), "
            "add a CHANGELOG.md entry, then follow docs/keel/release.md to tag."
        )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
