#!/usr/bin/env python3
"""Bump keel's version across every file a release must touch.

The version string lives in more places than is obvious, and two of them are
easy to miss by hand (they bit the 1.7.0 release):

- ``.claude-plugin/plugin.json`` — *not* regenerated by ``make plugin``; a stale
  value fails ``test_plugin_manifest_version_matches_keel_version``.
- every adapter surface embeds a ``keel_version=<v>`` marker, so the surfaces
  must be regenerated (``make plugin`` + ``make adapters``) after a bump or the
  drift test fails.

This script rewrites the *string* sources deterministically; the ``make
release-bump`` target runs it and then regenerates the surfaces. It deliberately
edits keel-repo-specific paths — it is a maintenance tool (sibling to
``release_smoke.py``), not a consumer-neutral ``keel`` CLI command.

Historical version mentions (e.g. "Since **1.6.5**" prose) are left untouched:
only the precise pinned-install (``keel@vX``) and badge (``>vX<``) forms and the
declared version assignments are rewritten.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SEMVER = re.compile(r"^\d+\.\d+\.\d+$")

# Repo root = parent of this script's directory (scripts/..).
DEFAULT_ROOT = Path(__file__).resolve().parent.parent


def current_version(root: Path) -> str:
    """Read the declared version from ``pyproject.toml``."""
    text = (root / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version = "([^"]+)"', text, re.MULTILINE)
    if not match:
        raise ValueError("could not find `version = \"...\"` in pyproject.toml")
    return match.group(1)


def _edits(old: str, new: str) -> list[tuple[str, str, str]]:
    """Return ``(relative_path, find, replace)`` rewrites for ``old`` → ``new``.

    Each ``find`` is specific enough that only the version-bearing token is
    touched — never historical prose that happens to mention ``old``.
    """
    return [
        ("pyproject.toml", f'version = "{old}"', f'version = "{new}"'),
        ("src/keel/__init__.py", f'__version__ = "{old}"', f'__version__ = "{new}"'),
        (".claude-plugin/plugin.json", f'"version": "{old}"', f'"version": "{new}"'),
        ("README.md", f"keel@v{old}", f"keel@v{new}"),
        ("website/index.html", f"keel@v{old}", f"keel@v{new}"),
        ("website/index.html", f">v{old}<", f">v{new}<"),
        (".github/workflows/keel-ship.yml", f"keel@v{old}", f"keel@v{new}"),
    ]


def bump(root: Path, new: str) -> tuple[str, list[str]]:
    """Rewrite the version to ``new`` across the release files under ``root``.

    Returns ``(old_version, changed_relative_paths)``. A file whose ``find``
    token is absent is skipped (so re-running after a partial bump is safe).
    """
    if not SEMVER.match(new):
        raise ValueError(f"version must be X.Y.Z, got {new!r}")
    old = current_version(root)
    if old == new:
        return old, []
    changed: list[str] = []
    for rel, find, replace in _edits(old, new):
        path = root / rel
        text = path.read_text(encoding="utf-8")
        if find not in text:
            continue
        path.write_text(text.replace(find, replace), encoding="utf-8")
        if rel not in changed:
            changed.append(rel)
    return old, changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Bump keel's release version.")
    parser.add_argument("version", help="new version, X.Y.Z")
    parser.add_argument("--root", default=str(DEFAULT_ROOT),
                        help="repo root (defaults to the keel checkout)")
    args = parser.parse_args(argv)

    root = Path(args.root)
    try:
        old, changed = bump(root, args.version)
    except (ValueError, OSError) as exc:
        print(f"release-bump failed: {exc}", file=sys.stderr)
        return 1

    if not changed:
        print(f"release-bump: already at {args.version}; nothing to change")
        return 0

    print(f"release-bump: {old} -> {args.version}")
    for rel in changed:
        print(f"  updated {rel}")
    print("Next: `make plugin && make adapters` (regenerate keel_version markers), "
          "add a CHANGELOG.md entry, then follow docs/keel/release.md to tag.")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
