#!/usr/bin/env python3
"""The one table of version-bearing surfaces a keel release has to move.

The list used to live inside ``release_bump.py`` and only the bumper could read
it, so "did the bump reach every surface?" was answerable in exactly one place —
*after* someone ran the bump. Nothing checked the same list at tag time, which is
how ``docs.html``, ``coverage.html`` and ``content.js`` sat seven releases behind
(#796-era drift) and how a version could reach PyPI with a manifest still naming
the previous one.

So the table lives here, and both directions read it:

- ``scripts/release_bump.py`` rewrites each surface (``make release-bump``),
- ``scripts/release_check.py`` asserts each surface already agrees with the
  declared version (``make release-check``, and the publish workflow's build job
  before anything is uploaded).

A surface added to this table is therefore bumped *and* guarded by the same edit.
Adding it to only one of the two is no longer possible, which is the failure this
file exists to remove.

Two rewrite modes, and the difference is deliberate:

``by_shape=False`` (literal)
    The bump finds ``token`` spelled with the *current* version and replaces it.
    A file that has already fallen behind contains neither the old nor the new
    string and is left alone. That is the right behaviour where the same shape
    also appears as history a release must not rewrite — ``README.md`` may
    legitimately pin an older ``keel@vX.Y.Z`` in prose.

``by_shape=True``
    The bump rewrites whatever version the pattern finds. This re-syncs a file
    that has drifted, which is exactly what the site surfaces needed, and is the
    reason a deliberate historical pin must not be written as ``keel@vX.Y.Z``
    inside ``website/index.html`` or ``website/content.js``.

``pattern`` is the shape of ``token`` in both modes: the check reads it, and it
is what makes a drifted literal surface *visible* even though the bump will not
touch it.
"""

from __future__ import annotations

import re
from typing import NamedTuple

#: Shape of every version this project declares. Matches the bumper's own
#: ``SEMVER`` guard: keel does not ship pre-release or local-version tags.
VERSION_RE = r"\d+\.\d+\.\d+"


class Surface(NamedTuple):
    """One version-bearing token in one file."""

    #: Repo-relative path.
    path: str
    #: The token as it should read, with ``{version}`` where the version goes.
    #: Doubles as the bump's replacement text and the check's "expected" spelling.
    token: str
    #: Regex finding that token by shape; group ``version`` captures the version.
    pattern: str
    #: See the module docstring: shape rewrites re-sync a drifted file, literal
    #: rewrites refuse to touch anything but the current version.
    by_shape: bool


RELEASE_SURFACES: tuple[Surface, ...] = (
    # --- the declared version -------------------------------------------------
    Surface(
        "pyproject.toml",
        'version = "{version}"',
        rf'(?m)^version = "(?P<version>{VERSION_RE})"',
        False,
    ),
    Surface(
        "src/keel/__init__.py",
        '__version__ = "{version}"',
        rf'(?m)^__version__ = "(?P<version>{VERSION_RE})"',
        False,
    ),
    # --- plugin manifests: *not* regenerated by `make plugin` ------------------
    Surface(
        ".claude-plugin/plugin.json",
        '"version": "{version}"',
        rf'"version": "(?P<version>{VERSION_RE})"',
        False,
    ),
    Surface(
        ".codex-plugin/plugin.json",
        '"version": "{version}"',
        rf'"version": "(?P<version>{VERSION_RE})"',
        False,
    ),
    # --- pinned-install references a user copies ------------------------------
    Surface("README.md", "keel@v{version}", rf"keel@v(?P<version>{VERSION_RE})", False),
    Surface(
        ".github/workflows/keel-ship.yml",
        "keel@v{version}",
        rf"keel@v(?P<version>{VERSION_RE})",
        False,
    ),
    Surface(
        "docs/keel/cutover.md",
        "keel@v{version}",
        rf"keel@v(?P<version>{VERSION_RE})",
        False,
    ),
    # --- the formula `brew install` runs --------------------------------------
    Surface(
        "Formula/keel.rb",
        "/tags/v{version}.tar.gz",
        rf"/tags/v(?P<version>{VERSION_RE})\.tar\.gz",
        False,
    ),
    # --- the site's hardcoded fallbacks, matched by shape ---------------------
    Surface(
        "website/index.html",
        "keel@v{version}",
        rf"keel@v(?P<version>{VERSION_RE})",
        True,
    ),
    Surface(
        "website/index.html",
        "v{version}",
        rf"(?<=data-version>)v(?P<version>{VERSION_RE})",
        True,
    ),
    Surface(
        "website/docs.html",
        "v{version}",
        rf"(?<=data-version>)v(?P<version>{VERSION_RE})",
        True,
    ),
    Surface(
        "website/coverage.html",
        "v{version}",
        rf"(?<=data-version>)v(?P<version>{VERSION_RE})",
        True,
    ),
    Surface(
        "website/content.js",
        "v{version}",
        rf'(?<=version: ")v(?P<version>{VERSION_RE})',
        True,
    ),
    Surface(
        "website/content.js",
        "keel@v{version}",
        rf"keel@v(?P<version>{VERSION_RE})",
        True,
    ),
)


def literal_surfaces() -> tuple[Surface, ...]:
    """Surfaces the bump rewrites by finding the current version verbatim."""
    return tuple(surface for surface in RELEASE_SURFACES if not surface.by_shape)


def shape_surfaces() -> tuple[Surface, ...]:
    """Surfaces the bump rewrites by shape, re-syncing one that has drifted."""
    return tuple(surface for surface in RELEASE_SURFACES if surface.by_shape)


def versions_in(surface: Surface, text: str) -> list[str]:
    """Every version ``surface`` declares in ``text``, in file order."""
    return [match.group("version") for match in re.finditer(surface.pattern, text)]
